## Network Commands
[[snippets]]
description = "Check which process is using a specific port"
command = "lsof -i :<port> || echo 'No process found using port <port>'"
tag = ["lsof"]
output = ""

[[snippets]]
description = "Kill process using a specific port"
command = "lsof -ti :<port> | xargs kill -9"
tag = ["lsof"]
output = ""
