# General
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Extended keys
if-shell '[ -n "$GHOSTTY_RESOURCES_DIR" ]' {
    set -s extended-keys on
    set -as terminal-features 'xterm-ghostty:extkeys'
    bind-key -n S-Enter send-keys Escape "[13;2u"
}

# Window rename
set -g automatic-rename-format '#{?#{==:#{pane_current_command},zsh},#{?#{==:#{pane_current_path},/Users/imp.lin},~,#{b:pane_current_path}},#{pane_current_command}}'
set -g allow-rename off

# Prefix
set -g prefix C-b
bind C-b send-prefix

# Keybindings
bind-key x kill-pane
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window
bind N new-session
bind -n M-h resize-pane -L
bind -n M-l resize-pane -R
bind -n M-k resize-pane -U
bind -n M-j resize-pane -D
bind -n M-i swap-window -t -1
bind -n M-o swap-window -t +1

# Copy mode
# bind-key -T copy-mode MouseDragEnd1Pane send-keys -X stop-selection

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'roosta/tmux-fuzzback'
set -g @fuzzback-bind /
set -g @fuzzback-popup 1
set -g @fuzzback-popup-size '80%'
set -g @fuzzback-finder-bind 'ctrl-y:accept'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text "#W#F"
set -g @catppuccin_window_current_text "#W#F"
set -g @catppuccin_uptime_icon ""
set -g @catppuccin_window_current_number_color "#{@thm_mauve}"
set -g @catppuccin_window_current_text_color "#{@thm_mauve}"
set -g @catppuccin_window_number_color "#{@thm_overlay_2}"
set -g @catppuccin_window_text_color "#{@thm_overlay_2}"

# TPM
run '~/.tmux/plugins/tpm/tpm'

# Post-plugin overrides

# Window tab
set -g @_ctp_active "#[fg=#{@thm_crust},bg=#{@thm_mauve}]"
set -gF window-status-current-format "#{E:@_ctp_active}#{E:@catppuccin_window_current_left_separator}#{@catppuccin_window_current_number}"
set -agF window-status-current-format "#{E:@catppuccin_window_current_middle_separator}"
set -agF window-status-current-format "#{E:@_ctp_active}#{@catppuccin_window_current_text}#{E:@catppuccin_window_current_right_separator}"

set -g @_ctp_inactive "#[fg=#{@thm_crust},bg=#{@thm_overlay_2}]"
set -gF window-status-format "#{E:@_ctp_inactive}#{E:@catppuccin_window_left_separator}#{@catppuccin_window_number}"
set -agF window-status-format "#{E:@catppuccin_window_middle_separator}"
set -agF window-status-format "#{E:@_ctp_inactive}#{@catppuccin_window_text}#{E:@catppuccin_window_right_separator}"

# Status left
set -g status-left-length 50
set -gF @_session_color "#{@thm_peach}"
set -g @_ctp_session "#[fg=#{@_session_color},bg=default]#[fg=#{@thm_crust},bg=#{@_session_color}]###S /#{server_sessions}#[fg=#{@_session_color},bg=default] "
set -g status-left " #{E:@_ctp_session}"

# Hooks
set-hook -g client-session-changed {
    set -gF @_session_color "#{@thm_overlay_2}"
    run-shell -b 'sleep 0.1 && tmux set -gF @_session_color "#{@thm_peach}"'
}

# Status right
set -g status-right ""
set -ag status-right "#(~/.local/bin/tmux-session-uptime) "
set -ag status-right "#{?client_prefix,#[fg=#{@thm_red} bold]PREFIX ,#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold]COPY ,#[fg=#{@thm_green} bold]}}"
